name: detective_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - google-adk==1.19.0
      - google-genai==1.52.0
      - gradio==6.0.0
      - python-dotenv==1.2.1
      - reportlab==4.4.5
      - aiohttp==3.13.2
